<?php
/**
 * Copyright (c) 2023
 * MIT License
 * Module AnassTouatiCoder_InstantConfigurationCopy
 * Author Anass TOUATI anass1touati@gmail.com
 */

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Template $block */
/** @var Escaper $escaper */

$id = uniqid('AtouatiConfigPath');
$idValue = uniqid('AtouatiConfigvalue');

?>
<?php if ($block->getDisplayPath()): ?>
    <?= $block->getBreakLine() ? '<br/>' : '' ?>
    <strong><?= $escaper->escapeHtml(__('Path:')) ?> </strong>
    <span class=atouati-config-path><?= $escaper->escapeHtml($block->getPath()) ?></span>
    <button type="button" class="atouati-config-path-Copy" id="<?= $escaper->escapeHtmlAttr($id) ?>"
            data-path="<?= $escaper->escapeHtmlAttr($block->getPath()) ?>">
        <?= $escaper->escapeHtml(__('Copy Hint Path')) ?>
    </button>
    <br/>
<?php endif; ?>
<?php if ($block->getDisplayValue()): ?>
    <button type="button" data-field-value-type="<?= $escaper->escapeHtmlAttr($block->getFieldType()) ?>"
            class="atouati-config-value-Copy primary"
            id="<?= $escaper->escapeHtmlAttr($idValue) ?>"
            data-field-id="<?= $escaper->escapeHtmlAttr($block->getFieldId()) ?>">
        <?= $escaper->escapeHtml(__('Copy Value')) ?>
    </button>
<?php endif; ?>
