<?php
/**
 * Copyright (c) 2022
 * MIT License
 * Module AnassTouatiCoder_InstantConfigurationCopy
 * Author Anass TOUATI anass1touati@gmail.com
 */

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Template $block */
/** @var Escaper $escaper */

$id = uniqid('AtouatiConfigPath');
$idValue = uniqid('AtouatiConfigvalue');

?>
<?php if ($block->getDisplayPath()): ?>
    <?= $block->getBreakLine() ? '<br/>' : '' ?>
    <strong><?= $escaper->escapeHtml(__('Path:')) ?> </strong>
    <span class=atouati-config-path><?= $escaper->escapeHtml($block->getPath()) ?></span>
    <button type="button" class="atouati-config-path-Copy" id="<?= $escaper->escapeHtmlAttr($id) ?>"
            data-path="<?= $escaper->escapeHtmlAttr($block->getPath()) ?>">
        <?= $escaper->escapeHtml(__('Copy Hint Path')) ?>
    </button>
    <br/>
    <script>
        document.getElementById('<?= $escaper->escapeJs($id) ?>').addEventListener('click', (e) => {
            let element = e.target, id = element.id, path = element.dataset.path;
            navigator.clipboard.writeText(path);
            element.innerHTML = '<?= $escaper->escapeJs(__('Hint Path Copied'))?>';
            if (window.copy && window.copy !== id) {
                document.querySelector('#' + window.copy).innerHTML =
                    '<?= $escaper->escapeJs(__('Copy Hint Path'))?>';
            }
            window.copy = id;
        });
    </script>
<?php endif; ?>
<?php if ($block->getDisplayValue()): ?>
    <button type="button" data-field-value-type="<?= $escaper->escapeHtmlAttr($block->getFieldType()) ?>"
            class="atouati-config-value-Copy primary"
            id="<?= $escaper->escapeHtmlAttr($idValue) ?>"
            data-field-id="<?= $escaper->escapeHtmlAttr($block->getFieldId()) ?>">
        <?= $escaper->escapeHtml(__('Copy Value')) ?>
    </button>
<script>
    document.getElementById('<?= $escaper->escapeJs($idValue) ?>').addEventListener('click', (e) => {
        let element = e.target, id = element.id, fieldId = element.dataset.fieldId,
            value = false;
        if (element.dataset.fieldValueType === 'multiselect') {
            let selectedValues = [];
            let multiSelectElement = document.getElementById(fieldId);
            for (let i = 0; i < multiSelectElement.options.length; i++) {
                if (multiSelectElement.options[i].selected) {
                    selectedValues.push(multiSelectElement.options[i].value);
                }
            }
            value = selectedValues.join(', ');
        } else {
            let SelectedElement = document.getElementById(fieldId);
            console.log(fieldId);
            console.log(SelectedElement);
            if (SelectedElement.tagName === "TABLE") {
                // Do not support grid field

                return;
            }
            value = SelectedElement ? SelectedElement.value : false;
        }
        if (value === false) {
            return;
        }

        navigator.clipboard.writeText(value);
        element.innerHTML = '<?= $escaper->escapeHtml(__('Value Copied'))?>';
        if (window.copyValue && window.copyValue !== id) {
            document.querySelector('#' + window.copyValue).innerHTML = '<?= $escaper->escapeHtml(__('Copy Value'))?>';
        }
        window.copyValue = id;
    });
</script>
<?php endif;?>
