<?php
/**
 * Copyright (c) 2022
 * MIT License
 * Module AnassTouatiCoder_DiscountNotice
 * Author Anass TOUATI anass1touati@gmail.com
 */

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Template $block */
/** @var Escaper $escaper */

$id = uniqid('AtouatiConfigPath');

?>
<?= $block->getBreakLine() ? '<br>' : '' ?>
<strong><?= $escaper->escapeHtml(__('Path:'))?> </strong>
<span class=atouati-config-path><?= $escaper->escapeHtml($block->getPath()) ?></span>
<button type="button" class="atouati-config-path-Copy" id="<?= $escaper->escapeHtmlAttr($id) ?>"
        onclick="copy<?= $escaper->escapeJs($id) ?>('<?= $block->getPath() ?>',this)">
    <?= $escaper->escapeHtml(__('Copy Hint Path'))?>
</button>
<script>
    function copy<?= $escaper->escapeJs($id)  ?>(path, element) {
        let elementId = '<?= $id ?>';
        navigator.clipboard.writeText(path);
        element.innerHTML = '<?= $escaper->escapeHtml(__('Hint Path Copied'))?>';
        if (window.copy && window.copy !== elementId) {
            document.querySelector('#' + window.copy).innerHTML = '<?= $escaper->escapeHtml(__('Copy Hint Path'))?>';
        }
        window.copy = elementId;
    }
</script>
