<?php
/**
 * Copyright (c) 2023
 * MIT License
 * Module AnassTouatiCoder_InstantConfigurationCopy
 * Author Anass TOUATI anass1touati@gmail.com
 */

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Template $block */
/** @var Escaper $escaper */

$id = uniqid('AtouatiConfigModal');
?>
<div class="admin__field-tooltip" style="margin-left: 10px;margin-right: 20px;margin-top: -5px;">
    <a class="admin__field-tooltip-action action-help" id="tooltip_<?= /* @noEscape */ $id ?>" target="_blank"
       tabindex="1" attr="href: tooltip.link">
        <span></span>
    </a>
</div>

<div id="popup-modal-main_<?= /* @noEscape */ $id ?>" style="display:none;text-align: start;">
    <?= /* @noEscape */
    $block->getToolTipContent(); ?>
</div>
<script>
    require([
        'Magento_Ui/js/modal/modal'
    ], function (modal) {
        $(document).ready(function () {
            var options = {
                type: 'popup',
                responsive: true,
                innerScroll: true,
                title: '<?= /* @noEscape */ __('Children scopes:') ?>'
            };
            $("#tooltip_<?= /* @noEscape */ $id ?>").on('click', function () {
                $("#popup-modal-main_<?= /* @noEscape */ $id ?>").modal(options).modal('openModal');
            });
        });
    });
</script>
